#!/bin/bash

#updating and installing requirements
sudo apt update
sudo apt install python3
sudo apt install python3-pip

pip3 install watchdog

echo "please read README.md for informations about formating feature"
while true; do
    read -p "Do you wish to enable the formating feature?(default: no) " yn
    case $yn in
        [Yy]* ) format_enabled=( "y" ); break;;
        ""* ) format_enabled=( "n" ); break;;
        [Nn]* ) format_enabled=( "n" ); break;;
        * ) echo "Please answer yes or no.";;
    esac
done

if [ format_enabled == "y" ]; then
    sudo mkdir /home/$(id -un)/.downloads_organizer
    sudo cp src/main.py /home/$(id -un)/.downloads_organizer
    sudo cp crontab_format /etc/cron.d/
    
    python3 src/main.py $(id -un) -format &
else
    sudo mkdir /home/$(id -un)/.downloads_organizer
    sudo cp src/main.py /home/$(id -un)/.downloads_organizer
    sudo cp crontab /etc/cron.d/
    
    python3 src/main.py $(id -un) &
fi